### ISSUE TITLE
Incompatibility with Terminus 3

### ISSUE THREAD

**Issue by joshualieb** [pantheon-systems/terminus-newrelic-data-plugin#17]
Plugin fails on Terminus 3, previously worked (with some known issues) on v2.

> joshualieb@Joshuas-MacBook-Pro ~ % terminus self:info
>  ------------------------- ---------------------------------------------------------------------------------------------------
>   PHP binary                /usr/local/Cellar/php@7.4/7.4.27/bin/php
>   PHP version               7.4.27
>   php.ini used              /usr/local/etc/php/7.4/php.ini
>   Terminus project config
>   Terminus root dir         phar:///Users/joshualieb/terminus/terminus
>   Terminus version          3.0.3
>   Operating system          Darwin Kernel Version 19.6.0: Thu Jan 13 01:26:33 PST 2022; root:xnu-6153.141.51~3/RELEASE_X86_64
>  ------------------------- ---------------------------------------------------------------------------------------------------

Tested: site-specific new relic: 

> joshualieb@Joshuas-MacBook-Pro ~ % terminus newrelic-data:site databricks.live
> PHP Fatal error:  Uncaught Error: Class 'League\CLImate\CLImate' not found in /Users/joshualieb/repos/terminus-newrelic-data-plugin/src/Commands/GetNewrelicCommand.php:223
> Stack trace:
> #0 [internal function]: Pantheon\TerminusGetNewrelic\Commands\GetNewrelicCommand->site('databricks.live', NULL, Array)
> #1 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
> #2 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #3 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #4 /Users/joshualieb/.terminus/terminus-dependen in /Users/joshualieb/repos/terminus-newrelic-data-plugin/src/Commands/GetNewrelicCommand.php on line 223
> 
> Fatal error: Uncaught Error: Class 'League\CLImate\CLImate' not found in /Users/joshualieb/repos/terminus-newrelic-data-plugin/src/Commands/GetNewrelicCommand.php:223
> Stack trace:
> #0 [internal function]: Pantheon\TerminusGetNewrelic\Commands\GetNewrelicCommand->site('databricks.live', NULL, Array)
> #1 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
> #2 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #3 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #4 /Users/joshualieb/.terminus/terminus-dependen in /Users/joshualieb/repos/terminus-newrelic-data-plugin/src/Commands/GetNewrelicCommand.php on line 223

Tested: Org overview:

> joshualieb@Joshuas-MacBook-Pro ~ % terminus newrelic-data:org bd6baa82-82c5-4fbe-82a8-e4392853c9a0 --overview
> PHP Fatal error:  Uncaught Error: Class 'League\CLImate\CLImate' not found in /Users/joshualieb/repos/terminus-newrelic-data-plugin/src/Commands/GetNewrelicCommand.php:48
> Stack trace:
> #0 [internal function]: Pantheon\TerminusGetNewrelic\Commands\GetNewrelicCommand->org('bd6baa82-82c5-4...', NULL, Array)
> #1 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
> #2 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #3 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #4 /Users/joshualieb/.terminus/terminus-depende in /Users/joshualieb/repos/terminus-newrelic-data-plugin/src/Commands/GetNewrelicCommand.php on line 48
> 
> Fatal error: Uncaught Error: Class 'League\CLImate\CLImate' not found in /Users/joshualieb/repos/terminus-newrelic-data-plugin/src/Commands/GetNewrelicCommand.php:48
> Stack trace:
> #0 [internal function]: Pantheon\TerminusGetNewrelic\Commands\GetNewrelicCommand->org('bd6baa82-82c5-4...', NULL, Array)
> #1 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
> #2 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #3 /Users/joshualieb/.terminus/terminus-dependencies-2512c16/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #4 /Users/joshualieb/.terminus/terminus-depende in /Users/joshualieb/repos/terminus-newrelic-data-plugin/src/Commands/GetNewrelicCommand.php on line 48

**Comment by theambert** [comment]
After installing https://packagist.org/packages/league/climate, this plugin works albeit with a remaining error:

`PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/amberthompson/.terminus/terminus-dependencies-7422d8f8f1/vendor/league/climate/src/TerminalObject/Dynamic/Progress.php on line 216`

**Comment by greg-1-anderson** [comment]
Terminus plugins should not use climate.

**Comment by kporras07** [comment]
@joshualieb Climate has been removed from this plugin so it should now work in 8.2 after you update the plugin. Closing this issue but feel free to reopen if you hit any other issues
